// Generated by gencpp from file pi_tracker/SetCommand.msg
// DO NOT EDIT!


#ifndef PI_TRACKER_MESSAGE_SETCOMMAND_H
#define PI_TRACKER_MESSAGE_SETCOMMAND_H

#include <ros/service_traits.h>


#include <pi_tracker/SetCommandRequest.h>
#include <pi_tracker/SetCommandResponse.h>


namespace pi_tracker
{

struct SetCommand
{

typedef SetCommandRequest Request;
typedef SetCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommand
} // namespace pi_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pi_tracker::SetCommand > {
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::pi_tracker::SetCommand&) { return value(); }
};

template<>
struct DataType< ::pi_tracker::SetCommand > {
  static const char* value()
  {
    return "pi_tracker/SetCommand";
  }

  static const char* value(const ::pi_tracker::SetCommand&) { return value(); }
};


// service_traits::MD5Sum< ::pi_tracker::SetCommandRequest> should match 
// service_traits::MD5Sum< ::pi_tracker::SetCommand > 
template<>
struct MD5Sum< ::pi_tracker::SetCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pi_tracker::SetCommand >::value();
  }
  static const char* value(const ::pi_tracker::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pi_tracker::SetCommandRequest> should match 
// service_traits::DataType< ::pi_tracker::SetCommand > 
template<>
struct DataType< ::pi_tracker::SetCommandRequest>
{
  static const char* value()
  {
    return DataType< ::pi_tracker::SetCommand >::value();
  }
  static const char* value(const ::pi_tracker::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pi_tracker::SetCommandResponse> should match 
// service_traits::MD5Sum< ::pi_tracker::SetCommand > 
template<>
struct MD5Sum< ::pi_tracker::SetCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pi_tracker::SetCommand >::value();
  }
  static const char* value(const ::pi_tracker::SetCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pi_tracker::SetCommandResponse> should match 
// service_traits::DataType< ::pi_tracker::SetCommand > 
template<>
struct DataType< ::pi_tracker::SetCommandResponse>
{
  static const char* value()
  {
    return DataType< ::pi_tracker::SetCommand >::value();
  }
  static const char* value(const ::pi_tracker::SetCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PI_TRACKER_MESSAGE_SETCOMMAND_H
